---

- hosts: localhost
  connection: local
  tasks:
    - name: install base packages
      homebrew:
        package:
        - ack
        - ag
        - fd
        - coreutils
        - dos2unix
        - cmake
        - jq
        - tmux
        - tree
        - ttyrec
        - watch
        - wget
        - zsh
        - ispell
        - fzf
        - z
        - kubectl
        - asdf
        - gpg
        - neovim
        - docker
        - docker-compose
        - graphviz
        - colima

    - name: install cask
      homebrew_cask:
        package:
        - emacs
        - the-unarchiver
        - wechat
        - amethyst

    - name: install spacemacs
      git:
        repo: https://github.com/syl20bnr/spacemacs
        dest: ~/.emacs.d

    - name: Download spacevim
      get_url:
        url: https://spacevim.org/install.sh
        dest: /tmp/install_spacevim.sh
        mode: +x

    - name: install spacevim
      shell: sh /tmp/install_spacevim.sh

    - name: clone powerline fonts
      git:
        repo: https://github.com/powerline/fonts.git
        depth: 1
        dest: /tmp/fonts

    - name: install powerline fonts
      shell: bash /tmp/fonts/install.sh

    - name: install tpm
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm

    - name: install additional cask
      homebrew_cask:
        package:
        - gas-mask
        - hiddenbar
        - wechatwork
        - visual-studio-code
        - zoom
        - vlc
        - tecent-lemon
        - aria2gui
        - google-chrome
        - jietu
        - franz
        - neteasemusic
        - authy
        - ticktick
        - clashx
        - termius
        - youdaodict
        - 1password
        - intellij-idea
        - balenaetcher
