- hosts: localhost
  connection: local
  tasks:
    # cat vs_code_extensions_list.txt | xargs -n 1 code --install-extension
    - name: install additional packages
      kewlfft.aur.aur:
        use: yay
        name:
          - qv2ray-static-bin-nightly
          - franz-bin
          - authy
          - typora-free
          - nutstore-experimental
          - intellij-idea-ultimate-edition
          - jdk11-openjdk
          - sbt
          - scala

    - name: install entertainment packages
      kewlfft.aur.aur:
        use: yay
        name:
          - okular
          - code
          - screenkey
          - byzanz
